### ISSUE TITLE
No actions in Atom now

### ISSUE THREAD

**Issue by tan-wei** [Finnerale/autocomplete-crates#1]
- Atom 1.38.2-Windows-x64
- Rust 1.36.0-stable-Windows-MSVC

No autocomplete actions show when edit `Cargo.toml` with `depencies`. Maybe need some update?

**Comment by luleyleo** [comment]
I just came around to try it and everything worked fine (on Linux).
Just in case, make sure you have `[dependencies]` and not `[depencies]` :wink: 
Anyway, I can't reproduce it. So if there is an issue with your setup, you will have to find it on your own...
Also note the remark in the readme about creates.io being wierd in some cases.

**Comment by tan-wei** [comment]
Sorry for my misspell.😂 Maybe I should try to reinstall something.
